### ISSUE TITLE
Add GCC Linking exception (spdx: GCC-exception-2.0) to clarify linking the rust systemd library into non (L)GPL programs

### ISSUE THREAD

**Issue by jmesmon** [jmesmon/rust-systemd#127]
#92 brought up a question regarding linking this library with other rust programs. In order to clarify things with minimal changes, I think it would be best to add the standard GCC Linking exception (spdx: GCC-exception-2.0) to the license of rust-systemd. This exception is used (other than by gcc), by projects like libgit2.

The specific text is:

> In addition to the permissions in the GNU Lesser General Public License, the
> authors give you unlimited permission to link the compiled version of this
> library into combinations with other programs, and to distribute those programs
> without any restriction coming from the use of this library. (The Lesser
> General Public License restrictions do apply in other respects; for example,
> they cover modification of the library, and distribution when not linked into
> another program.)

We would also modify our `Cargo.toml` `license` fields from `LGPL-2.1+` to `LGPL-2.1+ WITH GCC-exception-2.0`

I've also included it in the README to cover _new_ contributions to the repo in #126 (so the list of folks here doesn't get longer for now).

I'm listing all the people who are listed as contributing code to this repo here. I'd appreciate if you could let me know if you agree (or don't mind, or don't think you've made a contribution sizable enough to warrant copyright coverage), or do not agree with these changes, or would prefer some other change. (I'll checkboxes/edit this comment to reflect the status).

- [x] @birkenfeld 
- [x] @ibotty 
- [x] @dongsupark 
- [x] @Drakulix
- [x] @ErichDonGubler 
- [x] @kchibisov 
- [x] @pajowu 
- [x] @bruceg 
- [x] @danstiner 
- [x] @starfys 
- [x] @lucab 
- [x] @mathstuf 
- [x] @jlebon 
- [x] @MJDSys 
- [x] @main-- 
- [x] @dbrgn 
- [x] @smmckay 
- [x] @tekjar 
- [x] @squidpickles 
- [x] @bvinc 
- [ ] @ente76 [no]

**Comment by birkenfeld** [comment]
I'm in the "not sizable enough" camp.

**Comment by ibotty** [comment]
I'm in the "not sizable enough" camp as well, but I support the license change nevertheless.

**Comment by dongsupark** [comment]
I'm in the "not sizable enough" camp as well.

**Comment by Drakulix** [comment]
Agree, but also "not sizable enough".

**Comment by kchibisov** [comment]
I'm in the "not sizable enough" camp as well.

**Comment by pajowu** [comment]
Agree, but prob. also not sizeable enough

**Comment by ErichDonGubler** [comment]
I support this, but I don't have any illusions that my contributions were sizable here. :)

**Comment by bruceg** [comment]
I'm in the "not sizable enough" camp, and I think my change has been reverted anyways.

**Comment by starfys** [comment]
Also not sizable enough

**Comment by danstiner** [comment]
Agree and not sizable enough.

**Comment by lucab** [comment]
I'm ok with the license tweak.

**Comment by mathstuf** [comment]
I agree with the license change.

**Comment by jlebon** [comment]
:+1: from me as well.

**Comment by MJDSys** [comment]
I'm not sure if I'm sizable enough either, but I agree with the change either way.

**Comment by main--** [comment]
:heavy_check_mark:

**Comment by dbrgn** [comment]
OK for me!

**Comment by ente76** [comment]
I oppose the requested change. 

1. There is no need to perform such change. Whoever wants to reuse the library in closed source can go an link it dynamically as allowed by the LGPL.
2. The GCC linking exception is supposed to be applied to the GPL to make it slightly like the LGPL. While not yet clarified for static linking, the intention of the LGPL is to be a GPL with linking exception.
3. In general I oppose any change that gets my for-free effort closer to support commercial projects. If a commercial project requires my support, I demand to receive a fair share of their earnings. If a for-free project wants an individual exception, the project should request such individual exception rather than a general change of licensing.

**Comment by smmckay** [comment]
Fine with me

**Comment by tekjar** [comment]
I don't mind

**Comment by jmesmon** [comment]
I want to thank everyone for helping me out on this by replying and letting me know your position.

@ente76 thanks for letting me know what your position is, I appreciate it.

>     1. There is no need to perform such change. Whoever wants to reuse the library in closed source can go an link it dynamically as allowed by the LGPL.

Unfortunately, there isn't a great story around dynamic linking in rust with cargo right now. I expect that any hurdle that requires one to do that would find it easier to provide an alternate interface to `libsystemd` (they'd still link dynamically with `libsystemd` of course, because there is no other way to link with it).

If anyone has a specific pattern in mind that makes dynamically linking with rust libraries line rust-systemd straight forward, I'd love to hear about it.
 
>     2. The GCC linking exception is supposed to be applied to the GPL to make it slightly like the LGPL. While not yet clarified for static linking, the intention of the LGPL is to be a GPL with linking exception.

This isn't quite the case. The linking exception (combined with the GPLv2, as it typically would be) allows more uses of a library licensed under it than the (plain) LGPLv2. In particular, the ability to replace the library with another version of the same library is no longer a requirement with the linker exception. This extra allowance is what makes it easier for proprietary applications to link to things like libgit2. I think your first point touches on this in it's references to dynamic linking (as dynamic linking is one piece of allowing replacement).

>     3. In general I oppose any change that gets my for-free effort closer to support commercial projects. If a commercial project requires my support, I demand to receive a fair share of their earnings. If a for-free project wants an individual exception, the project should request such individual exception rather than a general change of licensing.

I definitely understand the desire to have one's development effort support free software. Many of the application-type software components I write personally tend to use GPL licenses for this reason. The concern with the current licensing situation is that it's likely without change that a alternate rust-systemd would be written. The key balance I'm keeping in mind here is "how easy is this to replace with new code" vs "how difficult is it to deal with licensing". In this case, I think, personally, that using LGPL (ie: requiring distributed modifications be open source) with the addition of the linking exception (ie: allowing the widest use in applications possible without trying to get agreement from all past contributors) provides the right set of trade offs in this particular case of a wrapper around functionality provided by `libsystemd`.

**Comment by jmesmon** [comment]
Brian (@bvinc) replied affirmatively to this in a private email (thanks!).

It looks like we now have responses from all contributors (prior to the addition of the additional grant for new contributors in the README). In the next few days, I'm going to look over the options & code contributed by those who did not approve to determine if it needs to be removed.

Thanks again to everyone for helping me out with this by replying!
