### ISSUE TITLE
possible regression from 0.5 to 0.6

### ISSUE THREAD

**Issue by cgwalters** [jmesmon/rust-systemd#137]
See https://github.com/coreos/rpm-ostree/pull/2226

I didn't try to debug it much - it's possible there's a bug in our port, but it looks straightforward.  Filing this issue mostly as a communication mechanism.

**Comment by jlebon** [comment]
Yeah, I think we were just hitting up against one other API change, which was that the journal is no longer seeked to the beginning of the journal on open. I updated https://github.com/coreos/rpm-ostree/pull/2226 now.
