### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by ente76** [jmesmon/rust-systemd#161]
Commit e189f6ce737e648d18a69c11fc1b4753f9878fa2 is licensed under LGPL without any exception. The commit is currently offered to the public under LGPL with linking exception.

**Comment by jmesmon** [comment]
The content of that commit (specifically, the implementation of `Journal::open_files()` and `Journal::open_directory()`) was removed. This was mentioned in https://github.com/jmesmon/rust-systemd/pull/155. It was done in https://github.com/jmesmon/rust-systemd/pull/154.
