### ISSUE TITLE
Log level mismatch

### ISSUE THREAD

**Issue by mathstuf** [jmesmon/rust-systemd#23]
Levels come from the `log` crate via this enum:

```rust
pub enum LogLevel {
    Error,
    Warn,
    Info,
    Debug,
    Trace,
}
```

and internally are converted to levels via `mem::transmute`. However, this leaves us with this mapping:

LogLevel | journal level
-------- | -------------
`Error` | `LOG_EMERG`
`Warn` | `LOG_ALERT`
`Info` | `LOG_CRIT`
`Debug` | `LOG_ERR`
`Trace` | `LOG_WARNING`

Which seems…off :) . A `match` statement should be used instead.

**Comment by dbrgn** [comment]
Just stumbled over this.

@jmesmon any chance for a release with this fix soon-ish?

**Comment by jmesmon** [comment]
@dbrgn I've just done a release of 0.1.0, should have what you need.

**Comment by dbrgn** [comment]
@jmesmon Thanks!
