### ISSUE TITLE
char_or_null!() returns a pointer to freed memory

### ISSUE THREAD

**Issue by Dr-Emann** [jmesmon/rust-systemd#33]
In the implementation of the `char_or_null` macro, the pointer returned is into the created CString, which is freed on leaving the scope (see the docs for [`CString::as_ptr()`](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.as_ptr)).

**Comment by jmesmon** [comment]
I've pushed a fix for this (thanks for bringing it to my attention). Feel free to let me know if the change doesn't fix the issue completely.
