### ISSUE TITLE
`listen_fds` might be unsafe

### ISSUE THREAD

**Issue by oconnor663** [jmesmon/rust-systemd#34]
If the caller passes `unset_environment: true`, the underlying C function will `unsetenv` several variables. That doesn't synchronize with the `ENV_LOCK` that the Rust stdlib takes when it touches the environment. This might lead to UB if two threads write to the environment at the same time?

**Comment by lucab** [comment]
I think so. In POSIX world no env-related function is required to be reentrant/thread-safe, so anything can happen. That said, I'm not sure if it is enough to just explicitly document this or if we should instead go one step further and perform the env unsetting in the Rust glue logic.

**Comment by oconnor663** [comment]
Oh I hadn't thought of that. I like the idea of doing the unsets in Rust. I can try to put together a PR this morning. (Do we assume the set of variables unset by this function is stable?)
