### ISSUE TITLE
Propagating pkg-config error message from build.rs

### ISSUE THREAD

**Issue by PAStheLoD** [jmesmon/rust-systemd#42]
Hello,

During cross compilation pkg-config checks `$TARGET` and throws an error hinting at setting `PKG_CONFIG_ALLOW_CROSS=1`, but this is ignored by [the current build.rs](https://github.com/jmesmon/rust-systemd/blob/386f62b5c7184aed35280ef2d517a446a42de611/libsystemd-sys/build.rs#L7), making the problem hard to diagnose/fix for the users.

**Comment by jmesmon** [comment]
Yep, seems like we should print the pkg-config error if the envronment variable mechanism also fails.
