### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by vberger** [jmesmon/rust-systemd#49]
Hi, on [smithay](https://github.com/Smithay/smithay) we depend on your crate for logind support. However, currently all our builds fail on beta and nightly because of `mbox` which fails to build, and on which the current release 0.2.0 depends.

I see you have already merged a fix in #46, would it be possible to release a new version including this fix?

Thanks.

**Comment by jmesmon** [comment]
v0.3.0 has been released: https://crates.io/crates/systemd/0.3.0
